name: Deploy to Server

on:
 push:
    branches:
      - main

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Setup known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 39.105.21.143 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh root@39.105.21.143 'cd /home/admin/github && git pull'
